//
//  NoPLByteValues.h
//  NoPLc
//
//  Created by Brad Bambara on 4/26/12.
//  Copyright (c) 2012. All rights reserved.
//

#ifndef NoPLc_NoPLByteValues_h
#define NoPLc_NoPLByteValues_h

//typedefs for NoPL-specific types
typedef unsigned short NoPL_Index;
typedef unsigned char NoPL_Instruction;

//SYMBOL TABLES

//symbol table total sizes
#define NoPL_BYTE_BOOLEAN_TABLE_SIZE 1
#define NoPL_BYTE_NUMERIC_TABLE_SIZE 2
#define NoPL_BYTE_STRING_TABLE_SIZE 3
#define NoPL_BYTE_OBJECT_TABLE_SIZE 4

//literal primitives
#define NoPL_BYTE_LITERAL_NUMBER 5
#define NoPL_BYTE_LITERAL_BOOLEAN_TRUE 6
#define NoPL_BYTE_LITERAL_BOOLEAN_FALSE 7
#define NoPL_BYTE_LITERAL_STRING 8
#define NoPL_BYTE_LITERAL_NULL 9

//VARIABLE RETRIEVAL

#define NoPL_BYTE_VARIABLE_NUMBER 10
#define NoPL_BYTE_VARIABLE_BOOLEAN 11
#define NoPL_BYTE_VARIABLE_STRING 12
#define NoPL_BYTE_VARIABLE_OBJECT 13

//NUMERIC OPERATORS

#define NoPL_BYTE_NUMERIC_ADD 14
#define NoPL_BYTE_NUMERIC_SUBTRACT 15
#define NoPL_BYTE_NUMERIC_DIVIDE 16
#define NoPL_BYTE_NUMERIC_MULTIPLY 17
#define NoPL_BYTE_NUMERIC_EXPONENT 18
#define NoPL_BYTE_NUMERIC_MODULO 19
#define NoPL_BYTE_NUMERIC_INCREMENT 20
#define NoPL_BYTE_NUMERIC_DECREMENT 21
#define NoPL_BYTE_NUMERIC_ASSIGN 22
#define NoPL_BYTE_NUMERIC_ADD_ASSIGN 23
#define NoPL_BYTE_NUMERIC_SUBTRACT_ASSIGN 24
#define NoPL_BYTE_NUMERIC_DIVIDE_ASSIGN 25
#define NoPL_BYTE_NUMERIC_MULTIPLY_ASSIGN 26
#define NoPL_BYTE_NUMERIC_EXPONENT_ASSIGN 27
#define NoPL_BYTE_NUMERIC_MODULO_ASSIGN 28
#define NoPL_BYTE_NUMERIC_ABS_VALUE 29
#define NoPL_BYTE_NUMERIC_NEGATION 30
#define NoPL_BYTE_NUMERIC_LOGICAL_EQUALITY 31
#define NoPL_BYTE_NUMERIC_LOGICAL_INEQUALITY 32

//BOOLEAN OPERATORS

#define NoPL_BYTE_BOOLEAN_LOGICAL_EQUALITY 33
#define NoPL_BYTE_BOOLEAN_LOGICAL_INEQUALITY 34
#define NoPL_BYTE_BOOLEAN_AND 35
#define NoPL_BYTE_BOOLEAN_OR 36
#define NoPL_BYTE_BOOLEAN_LESS_THAN 37
#define NoPL_BYTE_BOOLEAN_LESS_THAN_EQUAL 38
#define NoPL_BYTE_BOOLEAN_GREATER_THAN 39
#define NoPL_BYTE_BOOLEAN_GREATER_THAN_EQUAL 40
#define NoPL_BYTE_BOOLEAN_NEGATION 41
#define NoPL_BYTE_BOOLEAN_ASSIGN 42

//STRING OPERATORS

#define NoPL_BYTE_STRING_LOGICAL_EQUALITY 43
#define NoPL_BYTE_STRING_LOGICAL_INEQUALITY 44
#define NoPL_BYTE_STRING_CONCAT 45
#define NoPL_BYTE_STRING_ASSIGN 46
#define NoPL_BYTE_STRING_CONCAT_ASSIGN 47
#define NoPL_BYTE_STRING_PRINT 48

//OBJECT OPERATORS

#define NoPL_BYTE_OBJECT_LOGICAL_EQUALITY 49
#define NoPL_BYTE_OBJECT_LOGICAL_INEQUALITY 50
#define NoPL_BYTE_OBJECT_ASSIGN 51

//FUNCTION CALLS

#define NoPL_BYTE_FUNCTION_CALL 52
#define NoPL_BYTE_FUNCTION_INDEX 53
#define NoPL_BYTE_ARG_NUMBER 54
#define NoPL_BYTE_ARG_STRING 55
#define NoPL_BYTE_ARG_BOOLEAN 56
#define NoPL_BYTE_ARG_OBJECT 57

//CONTROL FLOW

#define NoPL_BYTE_CONDITIONAL 58
#define NoPL_BYTE_SWITCH_CASE_BOOLEAN 59
#define NoPL_BYTE_SWITCH_CASE_NUMBER 60
#define NoPL_BYTE_SWITCH_CASE_STRING 61
#define NoPL_BYTE_BUFFER_MOVE_FORWARD 62
#define NoPL_BYTE_BUFFER_MOVE_BACKWARD 63
#define NoPL_BYTE_PROGRAM_EXIT 64

//RESOLVING USER-RETURNED VALUES

#define NoPL_BYTE_RESOLVE_RESULT_TO_NUMBER 65
#define NoPL_BYTE_RESOLVE_RESULT_TO_BOOLEAN 66
#define NoPL_BYTE_RESOLVE_RESULT_TO_STRING 67
#define NoPL_BYTE_RESOLVE_RESULT_TO_OBJECT 68

//CASTING

#define NoPL_BYTE_CAST_NUMBER_TO_BOOLEAN 69
#define NoPL_BYTE_CAST_NUMBER_TO_STRING 70

#define NoPL_BYTE_CAST_BOOLEAN_TO_NUMBER 71
#define NoPL_BYTE_CAST_BOOLEAN_TO_STRING 72

#define NoPL_BYTE_CAST_STRING_TO_NUMBER 73
#define NoPL_BYTE_CAST_STRING_TO_BOOLEAN 74

#define NoPL_BYTE_CAST_OBJECT_TO_STRING 75

//METADATA

#define NoPL_BYTE_METADATA 76

//DEBUGGING
#define NoPL_BYTE_DEBUG_LINE 77
#define NoPL_BYTE_DEBUG_VALUE_NUMBER 78
#define NoPL_BYTE_DEBUG_VALUE_BOOLEAN 79
#define NoPL_BYTE_DEBUG_VALUE_STRING 80
#define NoPL_BYTE_DEBUG_VALUE_OBJECT 81

#endif