/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g
 *     -                            On : 2014-04-08 14:47:42
 *     -                for the parser : NoPL_APIParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
NoPL_APIParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pNoPL_APIParser, which is returned from a call to NoPL_APIParserNew().
 *
 * The methods in pNoPL_APIParser are  as follows:
 *
 *  - 
 NoPL_APIParser_api_return
      pNoPL_APIParser->api(pNoPL_APIParser)
 *  - 
 NoPL_APIParser_statement_return
      pNoPL_APIParser->statement(pNoPL_APIParser)
 *  - 
 NoPL_APIParser_classDecl_return
      pNoPL_APIParser->classDecl(pNoPL_APIParser)
 *  - 
 NoPL_APIParser_functionDecl_return
      pNoPL_APIParser->functionDecl(pNoPL_APIParser)
 *  - 
 NoPL_APIParser_functionArg_return
      pNoPL_APIParser->functionArg(pNoPL_APIParser)
 *  - 
 NoPL_APIParser_returnType_return
      pNoPL_APIParser->returnType(pNoPL_APIParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_NoPL_APIParser_H
#define _NoPL_APIParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct NoPL_APIParser_Ctx_struct NoPL_APIParser, * pNoPL_APIParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

typedef struct NoPL_APIParser_api_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    NoPL_APIParser_api_return;



typedef struct NoPL_APIParser_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    NoPL_APIParser_statement_return;



typedef struct NoPL_APIParser_classDecl_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    NoPL_APIParser_classDecl_return;



typedef struct NoPL_APIParser_functionDecl_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    NoPL_APIParser_functionDecl_return;



typedef struct NoPL_APIParser_functionArg_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    NoPL_APIParser_functionArg_return;



typedef struct NoPL_APIParser_returnType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    NoPL_APIParser_returnType_return;




/** Context tracking structure for 
NoPL_APIParser

 */
struct NoPL_APIParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     NoPL_APIParser_api_return
     (*api)	(struct NoPL_APIParser_Ctx_struct * ctx);

     NoPL_APIParser_statement_return
     (*statement)	(struct NoPL_APIParser_Ctx_struct * ctx);

     NoPL_APIParser_classDecl_return
     (*classDecl)	(struct NoPL_APIParser_Ctx_struct * ctx);

     NoPL_APIParser_functionDecl_return
     (*functionDecl)	(struct NoPL_APIParser_Ctx_struct * ctx);

     NoPL_APIParser_functionArg_return
     (*functionArg)	(struct NoPL_APIParser_Ctx_struct * ctx);

     NoPL_APIParser_returnType_return
     (*returnType)	(struct NoPL_APIParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct NoPL_APIParser_Ctx_struct * ctx);
    void	    (*free)   (struct NoPL_APIParser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pNoPL_APIParser NoPL_APIParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pNoPL_APIParser NoPL_APIParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define API_ARG_DELIMITER      4
#define API_ARG_VARIADIC      5
#define API_COMMENT      6
#define API_DECL_BOOL      7
#define API_DECL_CLASS      8
#define API_DECL_NUMBER      9
#define API_DECL_OBJ      10
#define API_DECL_STRING      11
#define API_DECL_VOID      12
#define API_FUNCTIONS      13
#define API_ID      14
#define API_PAREN_CLOSE      15
#define API_PAREN_OPEN      16
#define API_SCOPE_CLOSE      17
#define API_SCOPE_OPEN      18
#define API_STATEMENT_DELIMITER      19
#define API_SUBSCRIPT_CLOSE      20
#define API_SUBSCRIPT_OPEN      21
#define API_WS      22
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for NoPL_APIParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
