//
//  NoPLByteValues.h
//  NoPLc
//
//  Created by Brad Bambara on 4/26/12.
//  Copyright (c) 2012 Small Planet Digital. All rights reserved.
//

#ifndef NoPLc_NoPLByteValues_h
#define NoPLc_NoPLByteValues_h

//typedefs for NoPL-specific types
typedef unsigned short NoPL_Index;
typedef unsigned char NoPL_Instruction;
typedef int NoPL_BufferMove;

//SYMBOL TABLES

//symbol table total sizes
#define NoPL_BYTE_BOOLEAN_TABLE_SIZE 1
#define NoPL_BYTE_NUMERIC_TABLE_SIZE 2
#define NoPL_BYTE_STRING_TABLE_SIZE 3

//literal primitives
#define NoPL_BYTE_LITERAL_NUMBER 4
#define NoPL_BYTE_LITERAL_BOOLEAN_TRUE 5
#define NoPL_BYTE_LITERAL_BOOLEAN_FALSE 6
#define NoPL_BYTE_LITERAL_STRING 7
#define NoPL_BYTE_LITERAL_NULL 8

//VARIABLE RETRIEVAL

#define NoPL_BYTE_VARIABLE_NUMBER 9
#define NoPL_BYTE_VARIABLE_BOOLEAN 10
#define NoPL_BYTE_VARIABLE_STRING 11
#define NoPL_BYTE_VARIABLE_OBJECT 12

//NUMERIC OPERATORS

#define NoPL_BYTE_NUMERIC_ADD 13
#define NoPL_BYTE_NUMERIC_SUBTRACT 14
#define NoPL_BYTE_NUMERIC_DIVIDE 15
#define NoPL_BYTE_NUMERIC_MULTIPLY 16
#define NoPL_BYTE_NUMERIC_EXPONENT 17
#define NoPL_BYTE_NUMERIC_MODULO 18
#define NoPL_BYTE_NUMERIC_INCREMENT 19
#define NoPL_BYTE_NUMERIC_DECREMENT 20
#define NoPL_BYTE_NUMERIC_ASSIGN 21
#define NoPL_BYTE_NUMERIC_ADD_ASSIGN 22
#define NoPL_BYTE_NUMERIC_SUBTRACT_ASSIGN 23
#define NoPL_BYTE_NUMERIC_DIVIDE_ASSIGN 24
#define NoPL_BYTE_NUMERIC_MULTIPLY_ASSIGN 25
#define NoPL_BYTE_NUMERIC_EXPONENT_ASSIGN 26
#define NoPL_BYTE_NUMERIC_MODULO_ASSIGN 27
#define NoPL_BYTE_NUMERIC_ABS_VALUE 28
#define NoPL_BYTE_NUMERIC_NEGATION 29

//BOOLEAN OPERATORS

#define NoPL_BYTE_BOOLEAN_EQUALITY 30
#define NoPL_BYTE_BOOLEAN_INEQUALITY 31
#define NoPL_BYTE_BOOLEAN_AND 32
#define NoPL_BYTE_BOOLEAN_OR 33
#define NoPL_BYTE_BOOLEAN_LESS_THAN 34
#define NoPL_BYTE_BOOLEAN_LESS_THAN_EQUAL 35
#define NoPL_BYTE_BOOLEAN_GREATER_THAN 36
#define NoPL_BYTE_BOOLEAN_GREATER_THAN_EQUAL 37
#define NoPL_BYTE_BOOLEAN_NEGATION 38
#define NoPL_BYTE_BOOLEAN_ASSIGN 39

//STRING OPERATORS

#define NoPL_BYTE_STRING_CONCAT 40
#define NoPL_BYTE_STRING_ASSIGN 41
#define NoPL_BYTE_STRING_CONCAT_ASSIGN 42
#define NoPL_BYTE_STRING_PRINT 43

//OBJECT OPERATORS

#define NoPL_BYTE_OBJECT_ASSIGN 44

//FUNCTION CALLS

#define NoPL_BYTE_FUNCTION_CALL 45
#define NoPL_BYTE_FUNCTION_INDEX 46
#define NoPL_BYTE_ARG_NUMBER 47
#define NoPL_BYTE_ARG_STRING 48
#define NoPL_BYTE_ARG_BOOLEAN 49
#define NoPL_BYTE_ARG_OBJECT 50

//CONTROL FLOW

#define NoPL_BYTE_CONDITIONAL 51
#define NoPL_BYTE_BUFFER_MOVE 52
#define NoPL_BYTE_PROGRAM_EXIT 53

//RESOLVING USER-RETURNED VALUES

#define NoPL_BYTE_RESOLVE_RESULT_TO_NUMBER 54
#define NoPL_BYTE_RESOLVE_RESULT_TO_BOOLEAN 55
#define NoPL_BYTE_RESOLVE_RESULT_TO_STRING 56
#define NoPL_BYTE_RESOLVE_RESULT_TO_OBJECT 57

//CASTING

#define NoPL_BYTE_CAST_NUMBER_TO_BOOLEAN 58
#define NoPL_BYTE_CAST_NUMBER_TO_STRING 59

#define NoPL_BYTE_CAST_BOOLEAN_TO_NUMBER 60
#define NoPL_BYTE_CAST_BOOLEAN_TO_STRING 61

#define NoPL_BYTE_CAST_STRING_TO_NUMBER 62
#define NoPL_BYTE_CAST_STRING_TO_BOOLEAN 63

//DEBUGGING
#define NoPL_BYTE_DEBUG_LINE 64

////TODO: optimization
//#define NoPL_BYTE_NUMERIC_CONSTANTS 4
//#define NoPL_BYTE_STRING_CONSTANTS 5

#endif