/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g
 *     -                            On : 2014-04-07 15:35:56
 *     -                 for the lexer : NoPL_APILexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
NoPL_APILexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pNoPL_APILexer, which is returned from a call to NoPL_APILexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pNoPL_APILexer are  as follows:
 *
 *  - 
 void
      pNoPL_APILexer->DECL_CLASS(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->DECL_NUMBER(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->DECL_BOOL(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->DECL_STRING(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->DECL_OBJ(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->DECL_VOID(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->ARG_DELIMITER(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->ARG_VARIADIC(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->SUBSCRIPT_OPEN(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->SUBSCRIPT_CLOSE(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->PAREN_OPEN(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->PAREN_CLOSE(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->SCOPE_OPEN(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->SCOPE_CLOSE(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->STATEMENT_DELIMITER(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->ID(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->COMMENT(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->WS(pNoPL_APILexer)
 *  - 
 void
      pNoPL_APILexer->Tokens(pNoPL_APILexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_NoPL_APILexer_H
#define _NoPL_APILexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct NoPL_APILexer_Ctx_struct NoPL_APILexer, * pNoPL_APILexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
NoPL_APILexer

 */
struct NoPL_APILexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mDECL_CLASS)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mDECL_NUMBER)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mDECL_BOOL)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mDECL_STRING)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mDECL_OBJ)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mDECL_VOID)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mARG_DELIMITER)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mARG_VARIADIC)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mSUBSCRIPT_OPEN)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mSUBSCRIPT_CLOSE)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mPAREN_OPEN)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mPAREN_CLOSE)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mSCOPE_OPEN)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mSCOPE_CLOSE)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mSTATEMENT_DELIMITER)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mID)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct NoPL_APILexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct NoPL_APILexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct NoPL_APILexer_Ctx_struct * ctx);
    void	    (*free)   (struct NoPL_APILexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pNoPL_APILexer NoPL_APILexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pNoPL_APILexer NoPL_APILexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define ARG_DELIMITER      4
#define ARG_VARIADIC      5
#define COMMENT      6
#define DECL_BOOL      7
#define DECL_CLASS      8
#define DECL_NUMBER      9
#define DECL_OBJ      10
#define DECL_STRING      11
#define DECL_VOID      12
#define FUNCTIONS      13
#define ID      14
#define PAREN_CLOSE      15
#define PAREN_OPEN      16
#define SCOPE_CLOSE      17
#define SCOPE_OPEN      18
#define STATEMENT_DELIMITER      19
#define SUBSCRIPT_CLOSE      20
#define SUBSCRIPT_OPEN      21
#define WS      22
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for NoPL_APILexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
