//
//  NoPLByteValues.h
//  NoPLc
//
//  Created by Brad Bambara on 4/26/12.
//  Copyright (c) 2012 Small Planet Digital. All rights reserved.
//

#ifndef NoPLc_NoPLByteValues_h
#define NoPLc_NoPLByteValues_h

//typedefs for NoPL-specific types
typedef unsigned short NoPL_Index;
typedef unsigned char NoPL_Instruction;
typedef int NoPL_BufferMove;

//SYMBOL TABLES

//symbol table total sizes
#define NoPL_BYTE_BOOLEAN_TABLE_SIZE 1
#define NoPL_BYTE_NUMERIC_TABLE_SIZE 2
#define NoPL_BYTE_STRING_TABLE_SIZE 3

//TODO: do this later
////listing of constant values
//#define NoPL_BYTE_NUMERIC_CONSTANTS 4
//#define NoPL_BYTE_STRING_CONSTANTS 5

//LITERALS

//literal primitives
#define NoPL_BYTE_LITERAL_NUMBER 6
#define NoPL_BYTE_LITERAL_BOOLEAN_TRUE 7
#define NoPL_BYTE_LITERAL_BOOLEAN_FALSE 8
#define NoPL_BYTE_LITERAL_STRING 9
#define NoPL_BYTE_LITERAL_NULL 10

//VARIABLE RETRIEVAL

#define NoPL_BYTE_VARIABLE_NUMBER 11
#define NoPL_BYTE_VARIABLE_BOOLEAN 12
#define NoPL_BYTE_VARIABLE_STRING 13
#define NoPL_BYTE_VARIABLE_OBJECT 14

//NUMERIC OPERATORS

#define NoPL_BYTE_NUMERIC_ADD 15
#define NoPL_BYTE_NUMERIC_SUBTRACT 16
#define NoPL_BYTE_NUMERIC_DIVIDE 17
#define NoPL_BYTE_NUMERIC_MULTIPLY 18
#define NoPL_BYTE_NUMERIC_EXPONENT 19
#define NoPL_BYTE_NUMERIC_MODULO 20
#define NoPL_BYTE_NUMERIC_INCREMENT 21
#define NoPL_BYTE_NUMERIC_DECREMENT 22
#define NoPL_BYTE_NUMERIC_ASSIGN 23
#define NoPL_BYTE_NUMERIC_ADD_ASSIGN 24
#define NoPL_BYTE_NUMERIC_SUBTRACT_ASSIGN 25
#define NoPL_BYTE_NUMERIC_DIVIDE_ASSIGN 26
#define NoPL_BYTE_NUMERIC_MULTIPLY_ASSIGN 27
#define NoPL_BYTE_NUMERIC_EXPONENT_ASSIGN 28
#define NoPL_BYTE_NUMERIC_MODULO_ASSIGN 29
#define NoPL_BYTE_NUMERIC_ABS_VALUE 100
#define NoPL_BYTE_NUMERIC_NEGATION 101

//BOOLEAN OPERATORS

#define NoPL_BYTE_BOOLEAN_EQUALITY 30
#define NoPL_BYTE_BOOLEAN_INEQUALITY 31
#define NoPL_BYTE_BOOLEAN_AND 32
#define NoPL_BYTE_BOOLEAN_OR 33
#define NoPL_BYTE_BOOLEAN_LESS_THAN 34
#define NoPL_BYTE_BOOLEAN_LESS_THAN_EQUAL 35
#define NoPL_BYTE_BOOLEAN_GREATER_THAN 36
#define NoPL_BYTE_BOOLEAN_GREATER_THAN_EQUAL 37
#define NoPL_BYTE_BOOLEAN_NEGATION 38
#define NoPL_BYTE_BOOLEAN_ASSIGN 39

//STRING OPERATORS

#define NoPL_BYTE_STRING_CONCAT 40
#define NoPL_BYTE_STRING_ASSIGN 41
#define NoPL_BYTE_STRING_CONCAT_ASSIGN 42
#define NoPL_BYTE_STRING_PRINT 102

//OBJECT OPERATORS

#define NoPL_BYTE_OBJECT_TO_MEMBER 43
#define NoPL_BYTE_FUNCTION_ARG_COUNT 44
#define NoPL_BYTE_SUBSCRIPT 45
#define NoPL_BYTE_OBJECT_ASSIGN 46

//FUNCTION CALLS

#define NoPL_BYTE_ARG_NUMBER 59
#define NoPL_BYTE_ARG_STRING 60
#define NoPL_BYTE_ARG_BOOLEAN 61
#define NoPL_BYTE_ARG_OBJECT 62

//CONTROL FLOW

#define NoPL_BYTE_CONDITIONAL 47
#define NoPL_BYTE_BUFFER_MOVE 48
#define NoPL_BYTE_PROGRAM_EXIT 49

//CASTING

#define NoPL_BYTE_CAST_OBJECT_TO_NUMBER 50
#define NoPL_BYTE_CAST_OBJECT_TO_BOOLEAN 51
#define NoPL_BYTE_CAST_OBJECT_TO_STRING 52

#define NoPL_BYTE_CAST_NUMBER_TO_BOOLEAN 53
#define NoPL_BYTE_CAST_NUMBER_TO_STRING 54

#define NoPL_BYTE_CAST_BOOLEAN_TO_NUMBER 55
#define NoPL_BYTE_CAST_BOOLEAN_TO_STRING 56

#define NoPL_BYTE_CAST_STRING_TO_NUMBER 57
#define NoPL_BYTE_CAST_STRING_TO_BOOLEAN 58

//DEBUGGING
#define NoPL_BYTE_DEBUG_LINE 63

#endif