/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g
 *     -                            On : 2014-04-08 14:47:42
 *     -                for the parser : NoPL_APIParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "NoPL_APIParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pNoPL_APIParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pNoPL_APIParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pNoPL_APIParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pNoPL_APIParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   NoPL_APIParserTokenNames[19+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "API_ARG_DELIMITER",
        (pANTLR3_UINT8) "API_ARG_VARIADIC",
        (pANTLR3_UINT8) "API_COMMENT",
        (pANTLR3_UINT8) "API_DECL_BOOL",
        (pANTLR3_UINT8) "API_DECL_CLASS",
        (pANTLR3_UINT8) "API_DECL_NUMBER",
        (pANTLR3_UINT8) "API_DECL_OBJ",
        (pANTLR3_UINT8) "API_DECL_STRING",
        (pANTLR3_UINT8) "API_DECL_VOID",
        (pANTLR3_UINT8) "API_FUNCTIONS",
        (pANTLR3_UINT8) "API_ID",
        (pANTLR3_UINT8) "API_PAREN_CLOSE",
        (pANTLR3_UINT8) "API_PAREN_OPEN",
        (pANTLR3_UINT8) "API_SCOPE_CLOSE",
        (pANTLR3_UINT8) "API_SCOPE_OPEN",
        (pANTLR3_UINT8) "API_STATEMENT_DELIMITER",
        (pANTLR3_UINT8) "API_SUBSCRIPT_CLOSE",
        (pANTLR3_UINT8) "API_SUBSCRIPT_OPEN",
        (pANTLR3_UINT8) "API_WS"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 NoPL_APIParser_api_return
	api    (pNoPL_APIParser ctx);
static 
 NoPL_APIParser_statement_return
	statement    (pNoPL_APIParser ctx);
static 
 NoPL_APIParser_classDecl_return
	classDecl    (pNoPL_APIParser ctx);
static 
 NoPL_APIParser_functionDecl_return
	functionDecl    (pNoPL_APIParser ctx);
static 
 NoPL_APIParser_functionArg_return
	functionArg    (pNoPL_APIParser ctx);
static 
 NoPL_APIParser_returnType_return
	returnType    (pNoPL_APIParser ctx);
static void	NoPL_APIParserFree(pNoPL_APIParser ctx);
static void     NoPL_APIParserReset (pNoPL_APIParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new NoPL_APIParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pNoPL_APIParser
NoPL_APIParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return NoPL_APIParserNewSSD(instream, NULL);
}

/** \brief Create a new NoPL_APIParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pNoPL_APIParser
NoPL_APIParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pNoPL_APIParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pNoPL_APIParser) ANTLR3_CALLOC(1, sizeof(NoPL_APIParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in NoPL_APIParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our NoPL_APIParser interface
     */
    ctx->api	= api;
    ctx->statement	= statement;
    ctx->classDecl	= classDecl;
    ctx->functionDecl	= functionDecl;
    ctx->functionArg	= functionArg;
    ctx->returnType	= returnType;
    ctx->free			= NoPL_APIParserFree;
    ctx->reset			= NoPL_APIParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Create a LIST for recording rule memos.
     */
     RULEMEMO    = antlr3IntTrieNew(15);	/* 16 bit depth is enough for 32768 rules! */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = NoPL_APIParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
NoPL_APIParserReset (pNoPL_APIParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 NoPL_APIParserFree(pNoPL_APIParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);

	if	(RULEMEMO != NULL)
	{
		RULEMEMO->free(RULEMEMO);
		RULEMEMO = NULL;
	}
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return NoPL_APIParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_api61  */
static	ANTLR3_BITWORD FOLLOW_statement_in_api61_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001F80) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_api61	= { FOLLOW_statement_in_api61_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_api65  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_api65_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_api65	= { FOLLOW_EOF_in_api65_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classDecl_in_statement77  */
static	ANTLR3_BITWORD FOLLOW_classDecl_in_statement77_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classDecl_in_statement77	= { FOLLOW_classDecl_in_statement77_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_functionDecl_in_statement82  */
static	ANTLR3_BITWORD FOLLOW_functionDecl_in_statement82_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_functionDecl_in_statement82	= { FOLLOW_functionDecl_in_statement82_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_DECL_CLASS_in_classDecl93  */
static	ANTLR3_BITWORD FOLLOW_API_DECL_CLASS_in_classDecl93_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_DECL_CLASS_in_classDecl93	= { FOLLOW_API_DECL_CLASS_in_classDecl93_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ID_in_classDecl95  */
static	ANTLR3_BITWORD FOLLOW_API_ID_in_classDecl95_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000240000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ID_in_classDecl95	= { FOLLOW_API_ID_in_classDecl95_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_SUBSCRIPT_OPEN_in_classDecl98  */
static	ANTLR3_BITWORD FOLLOW_API_SUBSCRIPT_OPEN_in_classDecl98_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_SUBSCRIPT_OPEN_in_classDecl98	= { FOLLOW_API_SUBSCRIPT_OPEN_in_classDecl98_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_SUBSCRIPT_CLOSE_in_classDecl100  */
static	ANTLR3_BITWORD FOLLOW_API_SUBSCRIPT_CLOSE_in_classDecl100_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_SUBSCRIPT_CLOSE_in_classDecl100	= { FOLLOW_API_SUBSCRIPT_CLOSE_in_classDecl100_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_SCOPE_OPEN_in_classDecl104  */
static	ANTLR3_BITWORD FOLLOW_API_SCOPE_OPEN_in_classDecl104_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000021E80) };
static  ANTLR3_BITSET_LIST FOLLOW_API_SCOPE_OPEN_in_classDecl104	= { FOLLOW_API_SCOPE_OPEN_in_classDecl104_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_functionDecl_in_classDecl106  */
static	ANTLR3_BITWORD FOLLOW_functionDecl_in_classDecl106_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000021E80) };
static  ANTLR3_BITSET_LIST FOLLOW_functionDecl_in_classDecl106	= { FOLLOW_functionDecl_in_classDecl106_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_SCOPE_CLOSE_in_classDecl109  */
static	ANTLR3_BITWORD FOLLOW_API_SCOPE_CLOSE_in_classDecl109_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_API_SCOPE_CLOSE_in_classDecl109	= { FOLLOW_API_SCOPE_CLOSE_in_classDecl109_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_returnType_in_functionDecl138  */
static	ANTLR3_BITWORD FOLLOW_returnType_in_functionDecl138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_returnType_in_functionDecl138	= { FOLLOW_returnType_in_functionDecl138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ID_in_functionDecl140  */
static	ANTLR3_BITWORD FOLLOW_API_ID_in_functionDecl140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ID_in_functionDecl140	= { FOLLOW_API_ID_in_functionDecl140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_PAREN_OPEN_in_functionDecl143  */
static	ANTLR3_BITWORD FOLLOW_API_PAREN_OPEN_in_functionDecl143_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008EA0) };
static  ANTLR3_BITSET_LIST FOLLOW_API_PAREN_OPEN_in_functionDecl143	= { FOLLOW_API_PAREN_OPEN_in_functionDecl143_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_functionArg_in_functionDecl147  */
static	ANTLR3_BITWORD FOLLOW_functionArg_in_functionDecl147_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008010) };
static  ANTLR3_BITSET_LIST FOLLOW_functionArg_in_functionDecl147	= { FOLLOW_functionArg_in_functionDecl147_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ARG_DELIMITER_in_functionDecl150  */
static	ANTLR3_BITWORD FOLLOW_API_ARG_DELIMITER_in_functionDecl150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000EA0) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ARG_DELIMITER_in_functionDecl150	= { FOLLOW_API_ARG_DELIMITER_in_functionDecl150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_functionArg_in_functionDecl153  */
static	ANTLR3_BITWORD FOLLOW_functionArg_in_functionDecl153_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008010) };
static  ANTLR3_BITSET_LIST FOLLOW_functionArg_in_functionDecl153	= { FOLLOW_functionArg_in_functionDecl153_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_PAREN_CLOSE_in_functionDecl159  */
static	ANTLR3_BITWORD FOLLOW_API_PAREN_CLOSE_in_functionDecl159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_PAREN_CLOSE_in_functionDecl159	= { FOLLOW_API_PAREN_CLOSE_in_functionDecl159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_STATEMENT_DELIMITER_in_functionDecl162  */
static	ANTLR3_BITWORD FOLLOW_API_STATEMENT_DELIMITER_in_functionDecl162_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_API_STATEMENT_DELIMITER_in_functionDecl162	= { FOLLOW_API_STATEMENT_DELIMITER_in_functionDecl162_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_DECL_NUMBER_in_functionArg175  */
static	ANTLR3_BITWORD FOLLOW_API_DECL_NUMBER_in_functionArg175_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_DECL_NUMBER_in_functionArg175	= { FOLLOW_API_DECL_NUMBER_in_functionArg175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_DECL_BOOL_in_functionArg180  */
static	ANTLR3_BITWORD FOLLOW_API_DECL_BOOL_in_functionArg180_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_DECL_BOOL_in_functionArg180	= { FOLLOW_API_DECL_BOOL_in_functionArg180_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_DECL_STRING_in_functionArg185  */
static	ANTLR3_BITWORD FOLLOW_API_DECL_STRING_in_functionArg185_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_DECL_STRING_in_functionArg185	= { FOLLOW_API_DECL_STRING_in_functionArg185_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_DECL_OBJ_in_functionArg190  */
static	ANTLR3_BITWORD FOLLOW_API_DECL_OBJ_in_functionArg190_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_API_DECL_OBJ_in_functionArg190	= { FOLLOW_API_DECL_OBJ_in_functionArg190_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ID_in_functionArg194  */
static	ANTLR3_BITWORD FOLLOW_API_ID_in_functionArg194_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ID_in_functionArg194	= { FOLLOW_API_ID_in_functionArg194_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ARG_VARIADIC_in_functionArg199  */
static	ANTLR3_BITWORD FOLLOW_API_ARG_VARIADIC_in_functionArg199_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ARG_VARIADIC_in_functionArg199	= { FOLLOW_API_ARG_VARIADIC_in_functionArg199_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ARG_VARIADIC_in_functionArg202  */
static	ANTLR3_BITWORD FOLLOW_API_ARG_VARIADIC_in_functionArg202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ARG_VARIADIC_in_functionArg202	= { FOLLOW_API_ARG_VARIADIC_in_functionArg202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_API_ARG_VARIADIC_in_functionArg205  */
static	ANTLR3_BITWORD FOLLOW_API_ARG_VARIADIC_in_functionArg205_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_API_ARG_VARIADIC_in_functionArg205	= { FOLLOW_API_ARG_VARIADIC_in_functionArg205_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start api
 * /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:20:1: api : ( statement )* EOF !;
 */
static NoPL_APIParser_api_return
api(pNoPL_APIParser ctx)
{
    NoPL_APIParser_api_return retval;

    ANTLR3_UINT32 api_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    EOF2;
    NoPL_APIParser_statement_return statement1;
    #undef	RETURN_TYPE_statement1
    #define	RETURN_TYPE_statement1 NoPL_APIParser_statement_return

    pANTLR3_BASE_TREE EOF2_tree;

    /* Initialize rule variables
     */
    api_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(1)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    EOF2       = NULL;
    statement1.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    EOF2_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:21:2: ( ( statement )* EOF !)
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:21:4: ( statement )* EOF !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:21:4: ( statement )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case API_DECL_BOOL:
                case API_DECL_CLASS:
                case API_DECL_NUMBER:
                case API_DECL_OBJ:
                case API_DECL_STRING:
                case API_DECL_VOID:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:21:5: statement
            	    {
            	        FOLLOWPUSH(FOLLOW_statement_in_api61);
            	        statement1=statement(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleapiEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }

            	        if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, statement1.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


            EOF2 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_api65);
            if  (HASEXCEPTION())
            {
                goto ruleapiEx;
            }
            if (HASFAILED())
            {
                return retval;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleapiEx; /* Prevent compiler warnings */
    ruleapiEx: ;
    retval.stop = LT(-1);


    if ( BACKTRACKING==0 )
    {

    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    if ( BACKTRACKING>0 ) { MEMOIZE(1, api_StartIndex); }

    return retval;
}
/* $ANTLR end api */

/**
 * $ANTLR start statement
 * /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:24:1: statement : ( classDecl | functionDecl );
 */
static NoPL_APIParser_statement_return
statement(pNoPL_APIParser ctx)
{
    NoPL_APIParser_statement_return retval;

    ANTLR3_UINT32 statement_StartIndex;

    pANTLR3_BASE_TREE root_0;

    NoPL_APIParser_classDecl_return classDecl3;
    #undef	RETURN_TYPE_classDecl3
    #define	RETURN_TYPE_classDecl3 NoPL_APIParser_classDecl_return

    NoPL_APIParser_functionDecl_return functionDecl4;
    #undef	RETURN_TYPE_functionDecl4
    #define	RETURN_TYPE_functionDecl4 NoPL_APIParser_functionDecl_return


    /* Initialize rule variables
     */
    statement_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(2)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    classDecl3.tree = NULL;

    functionDecl4.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        {
            //  /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:25:2: ( classDecl | functionDecl )

            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) )
            {
            case API_DECL_CLASS:
            	{
            		alt2=1;
            	}
                break;
            case API_DECL_BOOL:
            case API_DECL_NUMBER:
            case API_DECL_OBJ:
            case API_DECL_STRING:
            case API_DECL_VOID:
            	{
            		alt2=2;
            	}
                break;

            default:
                if (BACKTRACKING>0)
                {
                    FAILEDFLAG = ANTLR3_TRUE;
                    return retval;
                }

                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulestatementEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:25:4: classDecl
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_classDecl_in_statement77);
        	        classDecl3=classDecl(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return retval;
        	        }

        	        if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, classDecl3.tree);

        	    }
        	    break;
        	case 2:
        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:26:4: functionDecl
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_functionDecl_in_statement82);
        	        functionDecl4=functionDecl(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return retval;
        	        }

        	        if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, functionDecl4.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;
    retval.stop = LT(-1);


    if ( BACKTRACKING==0 )
    {

    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    if ( BACKTRACKING>0 ) { MEMOIZE(2, statement_StartIndex); }

    return retval;
}
/* $ANTLR end statement */

/**
 * $ANTLR start classDecl
 * /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:29:1: classDecl : API_DECL_CLASS API_ID ( API_SUBSCRIPT_OPEN API_SUBSCRIPT_CLOSE )? API_SCOPE_OPEN ( functionDecl )* API_SCOPE_CLOSE -> ^( API_DECL_CLASS API_ID ^( API_FUNCTIONS ( functionDecl )* ) ( API_SUBSCRIPT_OPEN )? ) ;
 */
static NoPL_APIParser_classDecl_return
classDecl(pNoPL_APIParser ctx)
{
    NoPL_APIParser_classDecl_return retval;

    ANTLR3_UINT32 classDecl_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    API_DECL_CLASS5;
    pANTLR3_COMMON_TOKEN    API_ID6;
    pANTLR3_COMMON_TOKEN    API_SUBSCRIPT_OPEN7;
    pANTLR3_COMMON_TOKEN    API_SUBSCRIPT_CLOSE8;
    pANTLR3_COMMON_TOKEN    API_SCOPE_OPEN9;
    pANTLR3_COMMON_TOKEN    API_SCOPE_CLOSE11;
    NoPL_APIParser_functionDecl_return functionDecl10;
    #undef	RETURN_TYPE_functionDecl10
    #define	RETURN_TYPE_functionDecl10 NoPL_APIParser_functionDecl_return

    pANTLR3_BASE_TREE API_DECL_CLASS5_tree;
    pANTLR3_BASE_TREE API_ID6_tree;
    pANTLR3_BASE_TREE API_SUBSCRIPT_OPEN7_tree;
    pANTLR3_BASE_TREE API_SUBSCRIPT_CLOSE8_tree;
    pANTLR3_BASE_TREE API_SCOPE_OPEN9_tree;
    pANTLR3_BASE_TREE API_SCOPE_CLOSE11_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_API_SUBSCRIPT_CLOSE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_API_SCOPE_CLOSE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_API_SUBSCRIPT_OPEN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_API_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_API_DECL_CLASS;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_API_SCOPE_OPEN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_functionDecl;
    /* Initialize rule variables
     */
    classDecl_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(3)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    API_DECL_CLASS5       = NULL;
    API_ID6       = NULL;
    API_SUBSCRIPT_OPEN7       = NULL;
    API_SUBSCRIPT_CLOSE8       = NULL;
    API_SCOPE_OPEN9       = NULL;
    API_SCOPE_CLOSE11       = NULL;
    functionDecl10.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    API_DECL_CLASS5_tree   = NULL;
    API_ID6_tree   = NULL;
    API_SUBSCRIPT_OPEN7_tree   = NULL;
    API_SUBSCRIPT_CLOSE8_tree   = NULL;
    API_SCOPE_OPEN9_tree   = NULL;
    API_SCOPE_CLOSE11_tree   = NULL;

    stream_API_SUBSCRIPT_CLOSE   = NULL;
    #define CREATE_stream_API_SUBSCRIPT_CLOSE  if (stream_API_SUBSCRIPT_CLOSE == NULL) {stream_API_SUBSCRIPT_CLOSE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token API_SUBSCRIPT_CLOSE"); } 
    stream_API_SCOPE_CLOSE   = NULL;
    #define CREATE_stream_API_SCOPE_CLOSE  if (stream_API_SCOPE_CLOSE == NULL) {stream_API_SCOPE_CLOSE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token API_SCOPE_CLOSE"); } 
    stream_API_SUBSCRIPT_OPEN   = NULL;
    #define CREATE_stream_API_SUBSCRIPT_OPEN  if (stream_API_SUBSCRIPT_OPEN == NULL) {stream_API_SUBSCRIPT_OPEN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token API_SUBSCRIPT_OPEN"); } 
    stream_API_ID   = NULL;
    #define CREATE_stream_API_ID  if (stream_API_ID == NULL) {stream_API_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token API_ID"); } 
    stream_API_DECL_CLASS   = NULL;
    #define CREATE_stream_API_DECL_CLASS  if (stream_API_DECL_CLASS == NULL) {stream_API_DECL_CLASS = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token API_DECL_CLASS"); } 
    stream_API_SCOPE_OPEN   = NULL;
    #define CREATE_stream_API_SCOPE_OPEN  if (stream_API_SCOPE_OPEN == NULL) {stream_API_SCOPE_OPEN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token API_SCOPE_OPEN"); } 
    stream_functionDecl   = NULL;
    #define CREATE_stream_functionDecl  if (stream_functionDecl == NULL) {stream_functionDecl = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule functionDecl"); }

    retval.tree  = NULL;

    {
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:2: ( API_DECL_CLASS API_ID ( API_SUBSCRIPT_OPEN API_SUBSCRIPT_CLOSE )? API_SCOPE_OPEN ( functionDecl )* API_SCOPE_CLOSE -> ^( API_DECL_CLASS API_ID ^( API_FUNCTIONS ( functionDecl )* ) ( API_SUBSCRIPT_OPEN )? ) )
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:4: API_DECL_CLASS API_ID ( API_SUBSCRIPT_OPEN API_SUBSCRIPT_CLOSE )? API_SCOPE_OPEN ( functionDecl )* API_SCOPE_CLOSE
        {
            API_DECL_CLASS5 = (pANTLR3_COMMON_TOKEN) MATCHT(API_DECL_CLASS, &FOLLOW_API_DECL_CLASS_in_classDecl93);
            if  (HASEXCEPTION())
            {
                goto ruleclassDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
             
            if ( BACKTRACKING==0 ) { CREATE_stream_API_DECL_CLASS; stream_API_DECL_CLASS->add(stream_API_DECL_CLASS, API_DECL_CLASS5, NULL); }


            API_ID6 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ID, &FOLLOW_API_ID_in_classDecl95);
            if  (HASEXCEPTION())
            {
                goto ruleclassDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
             
            if ( BACKTRACKING==0 ) { CREATE_stream_API_ID; stream_API_ID->add(stream_API_ID, API_ID6, NULL); }


            // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:26: ( API_SUBSCRIPT_OPEN API_SUBSCRIPT_CLOSE )?
            {
                int alt3=2;
                switch ( LA(1) )
                {
                    case API_SUBSCRIPT_OPEN:
                    	{
                    		alt3=1;
                    	}
                        break;
                }

                switch (alt3)
                {
            	case 1:
            	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:27: API_SUBSCRIPT_OPEN API_SUBSCRIPT_CLOSE
            	    {
            	        API_SUBSCRIPT_OPEN7 = (pANTLR3_COMMON_TOKEN) MATCHT(API_SUBSCRIPT_OPEN, &FOLLOW_API_SUBSCRIPT_OPEN_in_classDecl98);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassDeclEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	         
            	        if ( BACKTRACKING==0 ) { CREATE_stream_API_SUBSCRIPT_OPEN; stream_API_SUBSCRIPT_OPEN->add(stream_API_SUBSCRIPT_OPEN, API_SUBSCRIPT_OPEN7, NULL); }


            	        API_SUBSCRIPT_CLOSE8 = (pANTLR3_COMMON_TOKEN) MATCHT(API_SUBSCRIPT_CLOSE, &FOLLOW_API_SUBSCRIPT_CLOSE_in_classDecl100);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassDeclEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	         
            	        if ( BACKTRACKING==0 ) { CREATE_stream_API_SUBSCRIPT_CLOSE; stream_API_SUBSCRIPT_CLOSE->add(stream_API_SUBSCRIPT_CLOSE, API_SUBSCRIPT_CLOSE8, NULL); }


            	    }
            	    break;

                }
            }

            API_SCOPE_OPEN9 = (pANTLR3_COMMON_TOKEN) MATCHT(API_SCOPE_OPEN, &FOLLOW_API_SCOPE_OPEN_in_classDecl104);
            if  (HASEXCEPTION())
            {
                goto ruleclassDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
             
            if ( BACKTRACKING==0 ) { CREATE_stream_API_SCOPE_OPEN; stream_API_SCOPE_OPEN->add(stream_API_SCOPE_OPEN, API_SCOPE_OPEN9, NULL); }


            // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:83: ( functionDecl )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case API_DECL_BOOL:
                case API_DECL_NUMBER:
                case API_DECL_OBJ:
                case API_DECL_STRING:
                case API_DECL_VOID:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:83: functionDecl
            	    {
            	        FOLLOWPUSH(FOLLOW_functionDecl_in_classDecl106);
            	        functionDecl10=functionDecl(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassDeclEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }

            	        if ( BACKTRACKING==0 ) { CREATE_stream_functionDecl; stream_functionDecl->add(stream_functionDecl, functionDecl10.tree, NULL); }

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


            API_SCOPE_CLOSE11 = (pANTLR3_COMMON_TOKEN) MATCHT(API_SCOPE_CLOSE, &FOLLOW_API_SCOPE_CLOSE_in_classDecl109);
            if  (HASEXCEPTION())
            {
                goto ruleclassDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
             
            if ( BACKTRACKING==0 ) { CREATE_stream_API_SCOPE_CLOSE; stream_API_SCOPE_CLOSE->add(stream_API_SCOPE_CLOSE, API_SCOPE_CLOSE11, NULL); }


            /* AST REWRITE
             * elements          : API_DECL_CLASS, API_ID, functionDecl, API_SUBSCRIPT_OPEN
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            if ( BACKTRACKING==0 ) 

            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 30:113: -> ^( API_DECL_CLASS API_ID ^( API_FUNCTIONS ( functionDecl )* ) ( API_SUBSCRIPT_OPEN )? )
            	{
            	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:116: ^( API_DECL_CLASS API_ID ^( API_FUNCTIONS ( functionDecl )* ) ( API_SUBSCRIPT_OPEN )? )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        stream_API_DECL_CLASS == NULL ? NULL : stream_API_DECL_CLASS->nextNode(stream_API_DECL_CLASS)
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, 
            	        stream_API_ID == NULL ? NULL : stream_API_ID->nextNode(stream_API_ID)
            	        );

            	        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:140: ^( API_FUNCTIONS ( functionDecl )* )
            	        {
            	            pANTLR3_BASE_TREE root_2 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	            root_2 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	            (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, API_FUNCTIONS, (pANTLR3_UINT8)"API_FUNCTIONS")
            	            , root_2));

            	            // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:156: ( functionDecl )*
            	            {
            	            	while ( (stream_functionDecl != NULL && stream_functionDecl->hasNext(stream_functionDecl))  )
            	            	{
            	            		ADAPTOR->addChild(ADAPTOR, root_2, stream_functionDecl == NULL ? NULL : stream_functionDecl->nextTree(stream_functionDecl));

            	            	}
            	            	if (stream_functionDecl != NULL) stream_functionDecl->reset(stream_functionDecl);

            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_1, root_2);
            	        }

            	        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:30:171: ( API_SUBSCRIPT_OPEN )?
            	        {
            	        	if ( (stream_API_SUBSCRIPT_OPEN != NULL && stream_API_SUBSCRIPT_OPEN->hasNext(stream_API_SUBSCRIPT_OPEN))  )
            	        	{
            	        		ADAPTOR->addChild(ADAPTOR, root_1, 
            	        		stream_API_SUBSCRIPT_OPEN == NULL ? NULL : stream_API_SUBSCRIPT_OPEN->nextNode(stream_API_SUBSCRIPT_OPEN)
            	        		);

            	        	}
            	        	if ( stream_API_SUBSCRIPT_OPEN != NULL) stream_API_SUBSCRIPT_OPEN->reset(stream_API_SUBSCRIPT_OPEN);

            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleclassDeclEx; /* Prevent compiler warnings */
    ruleclassDeclEx: ;
    retval.stop = LT(-1);


    if ( BACKTRACKING==0 )
    {

    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_API_SUBSCRIPT_CLOSE != NULL) stream_API_SUBSCRIPT_CLOSE->free(stream_API_SUBSCRIPT_CLOSE);
        if (stream_API_SCOPE_CLOSE != NULL) stream_API_SCOPE_CLOSE->free(stream_API_SCOPE_CLOSE);
        if (stream_API_SUBSCRIPT_OPEN != NULL) stream_API_SUBSCRIPT_OPEN->free(stream_API_SUBSCRIPT_OPEN);
        if (stream_API_ID != NULL) stream_API_ID->free(stream_API_ID);
        if (stream_API_DECL_CLASS != NULL) stream_API_DECL_CLASS->free(stream_API_DECL_CLASS);
        if (stream_API_SCOPE_OPEN != NULL) stream_API_SCOPE_OPEN->free(stream_API_SCOPE_OPEN);
        if (stream_functionDecl != NULL) stream_functionDecl->free(stream_functionDecl);
    }


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    if ( BACKTRACKING>0 ) { MEMOIZE(3, classDecl_StartIndex); }

    return retval;
}
/* $ANTLR end classDecl */

/**
 * $ANTLR start functionDecl
 * /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:33:1: functionDecl : returnType API_ID ^ API_PAREN_OPEN ! ( functionArg ( API_ARG_DELIMITER ! functionArg )* )? API_PAREN_CLOSE ! API_STATEMENT_DELIMITER !;
 */
static NoPL_APIParser_functionDecl_return
functionDecl(pNoPL_APIParser ctx)
{
    NoPL_APIParser_functionDecl_return retval;

    ANTLR3_UINT32 functionDecl_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    API_ID13;
    pANTLR3_COMMON_TOKEN    API_PAREN_OPEN14;
    pANTLR3_COMMON_TOKEN    API_ARG_DELIMITER16;
    pANTLR3_COMMON_TOKEN    API_PAREN_CLOSE18;
    pANTLR3_COMMON_TOKEN    API_STATEMENT_DELIMITER19;
    NoPL_APIParser_returnType_return returnType12;
    #undef	RETURN_TYPE_returnType12
    #define	RETURN_TYPE_returnType12 NoPL_APIParser_returnType_return

    NoPL_APIParser_functionArg_return functionArg15;
    #undef	RETURN_TYPE_functionArg15
    #define	RETURN_TYPE_functionArg15 NoPL_APIParser_functionArg_return

    NoPL_APIParser_functionArg_return functionArg17;
    #undef	RETURN_TYPE_functionArg17
    #define	RETURN_TYPE_functionArg17 NoPL_APIParser_functionArg_return

    pANTLR3_BASE_TREE API_ID13_tree;
    pANTLR3_BASE_TREE API_PAREN_OPEN14_tree;
    pANTLR3_BASE_TREE API_ARG_DELIMITER16_tree;
    pANTLR3_BASE_TREE API_PAREN_CLOSE18_tree;
    pANTLR3_BASE_TREE API_STATEMENT_DELIMITER19_tree;

    /* Initialize rule variables
     */
    functionDecl_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(4)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    API_ID13       = NULL;
    API_PAREN_OPEN14       = NULL;
    API_ARG_DELIMITER16       = NULL;
    API_PAREN_CLOSE18       = NULL;
    API_STATEMENT_DELIMITER19       = NULL;
    returnType12.tree = NULL;

    functionArg15.tree = NULL;

    functionArg17.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    API_ID13_tree   = NULL;
    API_PAREN_OPEN14_tree   = NULL;
    API_ARG_DELIMITER16_tree   = NULL;
    API_PAREN_CLOSE18_tree   = NULL;
    API_STATEMENT_DELIMITER19_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:34:2: ( returnType API_ID ^ API_PAREN_OPEN ! ( functionArg ( API_ARG_DELIMITER ! functionArg )* )? API_PAREN_CLOSE ! API_STATEMENT_DELIMITER !)
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:34:4: returnType API_ID ^ API_PAREN_OPEN ! ( functionArg ( API_ARG_DELIMITER ! functionArg )* )? API_PAREN_CLOSE ! API_STATEMENT_DELIMITER !
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_returnType_in_functionDecl138);
            returnType12=returnType(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunctionDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }

            if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, returnType12.tree);

            API_ID13 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ID, &FOLLOW_API_ID_in_functionDecl140);
            if  (HASEXCEPTION())
            {
                goto rulefunctionDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }

            if ( BACKTRACKING==0 ) {
            API_ID13_tree = 
            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_ID13))
            ;
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, API_ID13_tree, root_0));
            }

            API_PAREN_OPEN14 = (pANTLR3_COMMON_TOKEN) MATCHT(API_PAREN_OPEN, &FOLLOW_API_PAREN_OPEN_in_functionDecl143);
            if  (HASEXCEPTION())
            {
                goto rulefunctionDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }


            // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:34:39: ( functionArg ( API_ARG_DELIMITER ! functionArg )* )?
            {
                int alt6=2;
                switch ( LA(1) )
                {
                    case API_ARG_VARIADIC:
                    case API_DECL_BOOL:
                    case API_DECL_NUMBER:
                    case API_DECL_OBJ:
                    case API_DECL_STRING:
                    	{
                    		alt6=1;
                    	}
                        break;
                }

                switch (alt6)
                {
            	case 1:
            	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:34:40: functionArg ( API_ARG_DELIMITER ! functionArg )*
            	    {
            	        FOLLOWPUSH(FOLLOW_functionArg_in_functionDecl147);
            	        functionArg15=functionArg(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionDeclEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }

            	        if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, functionArg15.tree);

            	        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:34:52: ( API_ARG_DELIMITER ! functionArg )*

            	        for (;;)
            	        {
            	            int alt5=2;
            	            switch ( LA(1) )
            	            {
            	            case API_ARG_DELIMITER:
            	            	{
            	            		alt5=1;
            	            	}
            	                break;

            	            }

            	            switch (alt5)
            	            {
            	        	case 1:
            	        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:34:53: API_ARG_DELIMITER ! functionArg
            	        	    {
            	        	        API_ARG_DELIMITER16 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ARG_DELIMITER, &FOLLOW_API_ARG_DELIMITER_in_functionDecl150);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulefunctionDeclEx;
            	        	        }
            	        	        if (HASFAILED())
            	        	        {
            	        	            return retval;
            	        	        }


            	        	        FOLLOWPUSH(FOLLOW_functionArg_in_functionDecl153);
            	        	        functionArg17=functionArg(ctx);

            	        	        FOLLOWPOP();
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulefunctionDeclEx;
            	        	        }
            	        	        if (HASFAILED())
            	        	        {
            	        	            return retval;
            	        	        }

            	        	        if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, functionArg17.tree);

            	        	    }
            	        	    break;

            	        	default:
            	        	    goto loop5;	/* break out of the loop */
            	        	    break;
            	            }
            	        }
            	        loop5: ; /* Jump out to here if this rule does not match */


            	    }
            	    break;

                }
            }

            API_PAREN_CLOSE18 = (pANTLR3_COMMON_TOKEN) MATCHT(API_PAREN_CLOSE, &FOLLOW_API_PAREN_CLOSE_in_functionDecl159);
            if  (HASEXCEPTION())
            {
                goto rulefunctionDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }


            API_STATEMENT_DELIMITER19 = (pANTLR3_COMMON_TOKEN) MATCHT(API_STATEMENT_DELIMITER, &FOLLOW_API_STATEMENT_DELIMITER_in_functionDecl162);
            if  (HASEXCEPTION())
            {
                goto rulefunctionDeclEx;
            }
            if (HASFAILED())
            {
                return retval;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunctionDeclEx; /* Prevent compiler warnings */
    rulefunctionDeclEx: ;
    retval.stop = LT(-1);


    if ( BACKTRACKING==0 )
    {

    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    if ( BACKTRACKING>0 ) { MEMOIZE(4, functionDecl_StartIndex); }

    return retval;
}
/* $ANTLR end functionDecl */

/**
 * $ANTLR start functionArg
 * /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:37:1: functionArg : ( ( API_DECL_NUMBER ^| API_DECL_BOOL ^| API_DECL_STRING ^| API_DECL_OBJ ^) API_ID | API_ARG_VARIADIC ^ API_ARG_VARIADIC ! API_ARG_VARIADIC !);
 */
static NoPL_APIParser_functionArg_return
functionArg(pNoPL_APIParser ctx)
{
    NoPL_APIParser_functionArg_return retval;

    ANTLR3_UINT32 functionArg_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    API_DECL_NUMBER20;
    pANTLR3_COMMON_TOKEN    API_DECL_BOOL21;
    pANTLR3_COMMON_TOKEN    API_DECL_STRING22;
    pANTLR3_COMMON_TOKEN    API_DECL_OBJ23;
    pANTLR3_COMMON_TOKEN    API_ID24;
    pANTLR3_COMMON_TOKEN    API_ARG_VARIADIC25;
    pANTLR3_COMMON_TOKEN    API_ARG_VARIADIC26;
    pANTLR3_COMMON_TOKEN    API_ARG_VARIADIC27;

    pANTLR3_BASE_TREE API_DECL_NUMBER20_tree;
    pANTLR3_BASE_TREE API_DECL_BOOL21_tree;
    pANTLR3_BASE_TREE API_DECL_STRING22_tree;
    pANTLR3_BASE_TREE API_DECL_OBJ23_tree;
    pANTLR3_BASE_TREE API_ID24_tree;
    pANTLR3_BASE_TREE API_ARG_VARIADIC25_tree;
    pANTLR3_BASE_TREE API_ARG_VARIADIC26_tree;
    pANTLR3_BASE_TREE API_ARG_VARIADIC27_tree;

    /* Initialize rule variables
     */
    functionArg_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(5)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    API_DECL_NUMBER20       = NULL;
    API_DECL_BOOL21       = NULL;
    API_DECL_STRING22       = NULL;
    API_DECL_OBJ23       = NULL;
    API_ID24       = NULL;
    API_ARG_VARIADIC25       = NULL;
    API_ARG_VARIADIC26       = NULL;
    API_ARG_VARIADIC27       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    API_DECL_NUMBER20_tree   = NULL;
    API_DECL_BOOL21_tree   = NULL;
    API_DECL_STRING22_tree   = NULL;
    API_DECL_OBJ23_tree   = NULL;
    API_ID24_tree   = NULL;
    API_ARG_VARIADIC25_tree   = NULL;
    API_ARG_VARIADIC26_tree   = NULL;
    API_ARG_VARIADIC27_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:2: ( ( API_DECL_NUMBER ^| API_DECL_BOOL ^| API_DECL_STRING ^| API_DECL_OBJ ^) API_ID | API_ARG_VARIADIC ^ API_ARG_VARIADIC ! API_ARG_VARIADIC !)

            ANTLR3_UINT32 alt8;

            alt8=2;

            switch ( LA(1) )
            {
            case API_DECL_BOOL:
            case API_DECL_NUMBER:
            case API_DECL_OBJ:
            case API_DECL_STRING:
            	{
            		alt8=1;
            	}
                break;
            case API_ARG_VARIADIC:
            	{
            		alt8=2;
            	}
                break;

            default:
                if (BACKTRACKING>0)
                {
                    FAILEDFLAG = ANTLR3_TRUE;
                    return retval;
                }

                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto rulefunctionArgEx;

            }

            switch (alt8)
            {
        	case 1:
        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:4: ( API_DECL_NUMBER ^| API_DECL_BOOL ^| API_DECL_STRING ^| API_DECL_OBJ ^) API_ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:4: ( API_DECL_NUMBER ^| API_DECL_BOOL ^| API_DECL_STRING ^| API_DECL_OBJ ^)
        	        {
        	            int alt7=4;
        	            switch ( LA(1) )
        	            {
        	            case API_DECL_NUMBER:
        	            	{
        	            		alt7=1;
        	            	}
        	                break;
        	            case API_DECL_BOOL:
        	            	{
        	            		alt7=2;
        	            	}
        	                break;
        	            case API_DECL_STRING:
        	            	{
        	            		alt7=3;
        	            	}
        	                break;
        	            case API_DECL_OBJ:
        	            	{
        	            		alt7=4;
        	            	}
        	                break;

        	            default:
        	                if (BACKTRACKING>0)
        	                {
        	                    FAILEDFLAG = ANTLR3_TRUE;
        	                    return retval;
        	                }

        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 7;
        	                EXCEPTION->state        = 0;


        	                goto rulefunctionArgEx;

        	            }

        	            switch (alt7)
        	            {
        	        	case 1:
        	        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:5: API_DECL_NUMBER ^
        	        	    {
        	        	        API_DECL_NUMBER20 = (pANTLR3_COMMON_TOKEN) MATCHT(API_DECL_NUMBER, &FOLLOW_API_DECL_NUMBER_in_functionArg175);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulefunctionArgEx;
        	        	        }
        	        	        if (HASFAILED())
        	        	        {
        	        	            return retval;
        	        	        }

        	        	        if ( BACKTRACKING==0 ) {
        	        	        API_DECL_NUMBER20_tree = 
        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_DECL_NUMBER20))
        	        	        ;
        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, API_DECL_NUMBER20_tree, root_0));
        	        	        }

        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:24: API_DECL_BOOL ^
        	        	    {
        	        	        API_DECL_BOOL21 = (pANTLR3_COMMON_TOKEN) MATCHT(API_DECL_BOOL, &FOLLOW_API_DECL_BOOL_in_functionArg180);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulefunctionArgEx;
        	        	        }
        	        	        if (HASFAILED())
        	        	        {
        	        	            return retval;
        	        	        }

        	        	        if ( BACKTRACKING==0 ) {
        	        	        API_DECL_BOOL21_tree = 
        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_DECL_BOOL21))
        	        	        ;
        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, API_DECL_BOOL21_tree, root_0));
        	        	        }

        	        	    }
        	        	    break;
        	        	case 3:
        	        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:41: API_DECL_STRING ^
        	        	    {
        	        	        API_DECL_STRING22 = (pANTLR3_COMMON_TOKEN) MATCHT(API_DECL_STRING, &FOLLOW_API_DECL_STRING_in_functionArg185);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulefunctionArgEx;
        	        	        }
        	        	        if (HASFAILED())
        	        	        {
        	        	            return retval;
        	        	        }

        	        	        if ( BACKTRACKING==0 ) {
        	        	        API_DECL_STRING22_tree = 
        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_DECL_STRING22))
        	        	        ;
        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, API_DECL_STRING22_tree, root_0));
        	        	        }

        	        	    }
        	        	    break;
        	        	case 4:
        	        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:38:60: API_DECL_OBJ ^
        	        	    {
        	        	        API_DECL_OBJ23 = (pANTLR3_COMMON_TOKEN) MATCHT(API_DECL_OBJ, &FOLLOW_API_DECL_OBJ_in_functionArg190);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulefunctionArgEx;
        	        	        }
        	        	        if (HASFAILED())
        	        	        {
        	        	            return retval;
        	        	        }

        	        	        if ( BACKTRACKING==0 ) {
        	        	        API_DECL_OBJ23_tree = 
        	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_DECL_OBJ23))
        	        	        ;
        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, API_DECL_OBJ23_tree, root_0));
        	        	        }

        	        	    }
        	        	    break;

        	            }
        	        }

        	        API_ID24 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ID, &FOLLOW_API_ID_in_functionArg194);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulefunctionArgEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return retval;
        	        }

        	        if ( BACKTRACKING==0 ) {
        	        API_ID24_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_ID24));
        	        ADAPTOR->addChild(ADAPTOR, root_0, API_ID24_tree);
        	        }

        	    }
        	    break;
        	case 2:
        	    // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:39:4: API_ARG_VARIADIC ^ API_ARG_VARIADIC ! API_ARG_VARIADIC !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        API_ARG_VARIADIC25 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ARG_VARIADIC, &FOLLOW_API_ARG_VARIADIC_in_functionArg199);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulefunctionArgEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return retval;
        	        }

        	        if ( BACKTRACKING==0 ) {
        	        API_ARG_VARIADIC25_tree = 
        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, API_ARG_VARIADIC25))
        	        ;
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, API_ARG_VARIADIC25_tree, root_0));
        	        }

        	        API_ARG_VARIADIC26 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ARG_VARIADIC, &FOLLOW_API_ARG_VARIADIC_in_functionArg202);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulefunctionArgEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return retval;
        	        }


        	        API_ARG_VARIADIC27 = (pANTLR3_COMMON_TOKEN) MATCHT(API_ARG_VARIADIC, &FOLLOW_API_ARG_VARIADIC_in_functionArg205);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulefunctionArgEx;
        	        }
        	        if (HASFAILED())
        	        {
        	            return retval;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulefunctionArgEx; /* Prevent compiler warnings */
    rulefunctionArgEx: ;
    retval.stop = LT(-1);


    if ( BACKTRACKING==0 )
    {

    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    if ( BACKTRACKING>0 ) { MEMOIZE(5, functionArg_StartIndex); }

    return retval;
}
/* $ANTLR end functionArg */

/**
 * $ANTLR start returnType
 * /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:42:1: returnType : ( API_DECL_NUMBER | API_DECL_BOOL | API_DECL_STRING | API_DECL_OBJ | API_DECL_VOID ) ;
 */
static NoPL_APIParser_returnType_return
returnType(pNoPL_APIParser ctx)
{
    NoPL_APIParser_returnType_return retval;

    ANTLR3_UINT32 returnType_StartIndex;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set28;

    pANTLR3_BASE_TREE set28_tree;

    /* Initialize rule variables
     */
    returnType_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(6)) )
    {
    	retval.start = 0;

        {
        }



        return retval;
    }

    set28       = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    set28_tree   = NULL;


    retval.tree  = NULL;

    {
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:43:2: ( ( API_DECL_NUMBER | API_DECL_BOOL | API_DECL_STRING | API_DECL_OBJ | API_DECL_VOID ) )
        // /Users/bradbambara/Documents/CodeCheckout/NoPLGenerator/NoPL_repo/ANTLR_source/NoPL_API.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            set28=(pANTLR3_COMMON_TOKEN)LT(1);

            if ( LA(1) == API_DECL_BOOL || ((LA(1) >= API_DECL_NUMBER) && (LA(1) <= API_DECL_VOID)) )
            {
                CONSUME();
                if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, 
                (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set28))
                );
                PERRORRECOVERY=ANTLR3_FALSE;
                FAILEDFLAG=ANTLR3_FALSE;

            }
            else
            {
                if (BACKTRACKING>0)
                {
                    FAILEDFLAG = ANTLR3_TRUE;
                    return retval;
                }

                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto rulereturnTypeEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulereturnTypeEx; /* Prevent compiler warnings */
    rulereturnTypeEx: ;
    retval.stop = LT(-1);


    if ( BACKTRACKING==0 )
    {

    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    if ( BACKTRACKING>0 ) { MEMOIZE(6, returnType_StartIndex); }

    return retval;
}
/* $ANTLR end returnType */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
